package com.redhat.midstream.updater;

public enum CommitTaskType {
   SET_DOWNSTREAM_ISSUE_TARGET_RELEASE,
   ADD_DOWNSTREAM_ISSUE_LABEL,
   TRANSITION_DOWNSTREAM_ISSUE,
   CHERRY_PICK_UPSTREAM_COMMIT,
   CLONE_DOWNSTREAM_ISSUE,
   CLONE_UPSTREAM_ISSUE,
}
